#!/bin/bash


export ENV_NAME=default
export ENV_DIR="./envs/default"

## Discourse Vars
export DISCOURSE_ADMIN_USERNAME=
export DISCOURSE_ADMIN_PASSWORD=
export DISCOURSE_ADMIN_EMAIL=
export DISCOURSE_HOSTNAME=
export DISCOURSE_SITENAME=
## Setting DISCOURSE_REDIS_HOST will disable built in redis server
export DISCOURSE_REDIS_HOST=
export DISCOURSE_REDIS_PASSWORD=
## Setting DISCOURSE_POSTGRES_HOST will disable built in redis server
export DISCOURSE_POSTGRES_HOST=
export DISCOURSE_POSTGRES_ADMIN_PASSWORD=
export DISCOURSE_POSTGRES_USERNAME=
export DISCOURSE_POSTGRES_PASSWORD=
export DISCOURSE_POSTGRES_DATABASE=

export ROCKETCHAT_FQDN=
export ROCKETCHAT_SMTP_ENABLED=
export ROCKETCHAT_SMTP_USERNAME=
export ROCKETCHAT_SMTP_PASSWORD=
export ROCKETCHAT_SMTP_HOST=
export ROCKETCHAT_SMTP_PORT=
export ROCKETCHAT_MONGO_ROOT_PASSWORD=
export ROCKETCHAT_MONGO_USERNAME=
export ROCKETCHAT_MONGO_PASSWORD=
export ROCKETCHAT_MONGO_KEY=